// Code generated by libc-gen. DO NOT EDIT.

package micropython

import (
	"bytes"
	"math"
)

func (m *Module) _acos(x float64) float64 { return math.Acos(x) }

func (m *Module) _asin(x float64) float64 { return math.Asin(x) }

func (m *Module) _atan(x float64) float64     { return math.Atan(x) }
func (m *Module) _atan2(y, x float64) float64 { return math.Atan2(y, x) }

func (m *Module) _cos(x float64) float64 { return math.Cos(x) }

func (m *Module) _exp(x float64) float64 { return math.Exp(x) }

func (m *Module) _fmod(x, y float64) float64 { return math.Mod(x, y) }

func (m *Module) _frexp(x float64, eptr int32) float64 {
	x, exp := math.Frexp(x)
	store32(m.memory[uint32(eptr):], uint32(exp))
	return x
}
func (m *Module) _ldexp(x float64, n int32) float64 { return math.Ldexp(x, int(n)) }
func (m *Module) _log(x float64) float64            { return math.Log(x) }
func (m *Module) _memchr(s, c, n int32) int32 {
	b := m.memory[uint32(s):]
	if uint(len(b)) > uint(uint32(n)) {
		b = b[:uint32(n)]
	}
	if i := bytes.IndexByte(b, byte(c)); i >= 0 {
		return s + int32(i)
	}
	return 0
}

func (m *Module) _memcmp(s1, s2, n int32) int32 {
	e1, e2 := s1+n, s2+n
	b1 := m.memory[uint32(s1):uint32(e1)]
	b2 := m.memory[uint32(s2):uint32(e2)]
	return int32(bytes.Compare(b1, b2))
}

func (m *Module) _modf(x float64, iptr int32) (f float64) {
	if math.IsInf(x, 0) {
		f = math.Copysign(0, x)
	} else {
		x, f = math.Modf(x)
	}
	store64(m.memory[uint32(iptr):], math.Float64bits(x))
	return f
}
func (m *Module) _pow(x, y float64) float64 { return math.Pow(x, y) }

func (m *Module) _sin(x float64) float64 { return math.Sin(x) }

func (m *Module) _strchr(s, c int32) int32 {
	s = m._strchrnul(s, c)
	if m.memory[uint32(s)] == byte(c) {
		return s
	}
	return 0
}

func (m *Module) _strcmp(s1, s2 int32) int32 {
	b1 := m.memory[uint32(s1):]
	b2 := m.memory[uint32(s2):]
	sz := min(len(b1), len(b2))
	if i := bytes.IndexByte(b1[:sz], 0); i >= 0 {
		sz = i + 1
	}
	return int32(bytes.Compare(b1[:sz], b2[:sz]))
}
func (m *Module) _strlen(s int32) int32 {
	return int32(bytes.IndexByte(m.memory[uint32(s):], 0))
}

func (m *Module) _strncmp(s1, s2, n int32) int32 {
	b1 := m.memory[uint32(s1):]
	b2 := m.memory[uint32(s2):]
	sz := int(min(uint(len(b1)), uint(len(b2)), uint(uint32(n))))
	if i := bytes.IndexByte(b1[:sz], 0); i >= 0 {
		sz = i + 1
	}
	return int32(bytes.Compare(b1[:sz], b2[:sz]))
}
func (m *Module) _tan(x float64) float64 { return math.Tan(x) }

func (m *Module) _strchrnul(s, c int32) int32 {
	b := m.memory[uint32(s):]
	b = b[:bytes.IndexByte(b, 0)]
	sz := len(b)
	if c := byte(c); c != 0 {
		if i := bytes.IndexByte(b, c); i >= 0 {
			sz = i
		}
	}
	return s + int32(sz)
}
