// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I../../../build -I../../../build/build-embed -I../../../micropython -I../../../micropython/ports/embed -m32 abi_cgo.go

package abi

const (
	KindInvalid   = 0x0
	KindNull      = 0x1
	KindNone      = 0x2
	KindBool      = 0x3
	KindInt       = 0x4
	KindBigint    = 0x5
	KindFloat     = 0x6
	KindStr       = 0x7
	KindBytes     = 0x8
	KindTuple     = 0x9
	KindList      = 0xa
	KindDict      = 0xb
	KindObject    = 0xd
	KindRef       = 0xe
	KindException = 0xf
	KindSet       = 0x10
	KindFrozenSet = 0x11

	KindObjectIterable = 0x1
	KindObjectCallable = 0x2
)
