// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I../../../build -I../../../micropython -I../../../micropython/ports/embed -I../../../micropython/ports/embed/port -m32 errno_cgo.go

package abi

const (
	EPERM        = 0x1
	ENOENT       = 0x2
	EINTR        = 0x4
	EIO          = 0x5
	EBADF        = 0x9
	EAGAIN       = 0xb
	ENOMEM       = 0xc
	EACCES       = 0xd
	EFAULT       = 0xe
	EBUSY        = 0x10
	EEXIST       = 0x11
	EXDEV        = 0x12
	ENOTDIR      = 0x14
	EISDIR       = 0x15
	EINVAL       = 0x16
	ENFILE       = 0x17
	EMFILE       = 0x18
	EFBIG        = 0x1b
	ENOSPC       = 0x1c
	ESPIPE       = 0x1d
	EROFS        = 0x1e
	ENAMETOOLONG = 0x24
	ENOTEMPTY    = 0x27
	ELOOP        = 0x28
	EPIPE        = 0x20
	EOPNOTSUPP   = 0x5f
	EAFNOSUPPORT = 0x61
	EADDRINUSE   = 0x62
	ECONNABORTED = 0x67
	ECONNRESET   = 0x68
	ENOBUFS      = 0x69
	EISCONN      = 0x6a
	ENOTCONN     = 0x6b
	ETIMEDOUT    = 0x6e
	ECONNREFUSED = 0x6f
	EHOSTUNREACH = 0x71
	EALREADY     = 0x72
	EINPROGRESS  = 0x73
	ECANCELED    = 0x7d
)
