//go:generate sh -c "go tool cgo -godefs -- -I../../../build -I../../../build/build-embed -I../../../micropython -I../../../micropython/ports/embed -m32 abi_cgo.go > abi.go"
//go:generate go fmt ./...
package abi
